//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\Hotel.mdf;Integrated Se" +
            "curity=True;Connect Timeout=30;User Instance=True")]
        public string HotelConnectionString {
            get {
                return ((string)(this["HotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color roomLive {
            get {
                return ((global::System.Drawing.Color)(this["roomLive"]));
            }
            set {
                this["roomLive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color roomRepair {
            get {
                return ((global::System.Drawing.Color)(this["roomRepair"]));
            }
            set {
                this["roomRepair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color roomReserved {
            get {
                return ((global::System.Drawing.Color)(this["roomReserved"]));
            }
            set {
                this["roomReserved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DodgerBlue")]
        public global::System.Drawing.Color roomCleaning {
            get {
                return ((global::System.Drawing.Color)(this["roomCleaning"]));
            }
            set {
                this["roomCleaning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color roomEmpty {
            get {
                return ((global::System.Drawing.Color)(this["roomEmpty"]));
            }
            set {
                this["roomEmpty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color roomNeedClean {
            get {
                return ((global::System.Drawing.Color)(this["roomNeedClean"]));
            }
            set {
                this["roomNeedClean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool roomTableStyleFull {
            get {
                return ((bool)(this["roomTableStyleFull"]));
            }
            set {
                this["roomTableStyleFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("105, 72")]
        public global::System.Drawing.Size roomButtonSize {
            get {
                return ((global::System.Drawing.Size)(this["roomButtonSize"]));
            }
            set {
                this["roomButtonSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("105*72")]
        public string roomButtonSizeComboxSelcet {
            get {
                return ((string)(this["roomButtonSizeComboxSelcet"]));
            }
            set {
                this["roomButtonSizeComboxSelcet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("房类")]
        public string roomButtonSecondLine {
            get {
                return ((string)(this["roomButtonSecondLine"]));
            }
            set {
                this["roomButtonSecondLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("姓名")]
        public string roomButtonThirdLine {
            get {
                return ((string)(this["roomButtonThirdLine"]));
            }
            set {
                this["roomButtonThirdLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("客人类型")]
        public string roomButtonForthLine {
            get {
                return ((string)(this["roomButtonForthLine"]));
            }
            set {
                this["roomButtonForthLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal roomToReserved {
            get {
                return ((decimal)(this["roomToReserved"]));
            }
            set {
                this["roomToReserved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal roomReservedToCancle {
            get {
                return ((decimal)(this["roomReservedToCancle"]));
            }
            set {
                this["roomReservedToCancle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal roomButtonFontNumber {
            get {
                return ((decimal)(this["roomButtonFontNumber"]));
            }
            set {
                this["roomButtonFontNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("微软雅黑, 8.25pt")]
        public global::System.Drawing.Font roomButtonFont {
            get {
                return ((global::System.Drawing.Font)(this["roomButtonFont"]));
            }
            set {
                this["roomButtonFont"] = value;
            }
        }
    }
}
